[CYB-4;CYB-137] TableAPI Flink Indexer + Parser UI updates
cloudera/cybersec pull request #38
Opened 2023-06-12 17:30 UTC by stas-panasiuk

TableAPI Flink Hive Indexing implementation;
Parser ui allows user to choose from columns defined in indexing schema

2023-06-21 11:40 UTC, vpavlenko-cv commented
UI looks good

2023-06-28 08:52 UTC, vpavlenko-cv approved these changes

2023-07-01 18:35 UTC, carolynduby requested changes
Please check the scripts and provide an example config.

2023-07-01 18:35 UTC, carolynduby commented on flink-cyber/cyber-jobs/src/main/resources/conf/templates/index/index.properties.template
> +#Uncomment following two lines in case flink.writer=tableapi is specified
Please change the template so the can uncomment the lines without having to adjust the path.  For example:

#flink.tables-init-file=PIPELINE/triage/table-config.json
#flink.mapping-file=PIPELINE/triage/mapping-config.json

2023-07-01 18:35 UTC, carolynduby commented on flink-cyber/cyber-jobs/src/main/resources/conf/templates/index/index.properties.template
> +
Also please provide example table-config.json and mapping-config.json files.

2023-07-01 18:35 UTC, carolynduby commented on flink-cyber/flink-indexing/flink-indexing-hive/README.md
> +TableAPI writer is an optimized version that aims to provide both better performance and and ability to have multiple outputs.
correct "and and"

2023-07-01 18:35 UTC, carolynduby commented on flink-cyber/cyber-jobs/src/main/resources/scripts/cs-restart-index
> +cs-start-job -j flink-indexing-hive -y $pipeline/index/conf -p /etc/cybersec/conf/triage.properties -p kafka.properties -p "$generated_index_props" "${ship_configs[@]}"
do the table indexing configurations need to be shipped?
It looks like the client reads them at startup?

2023-07-12 19:59 UTC, carolynduby approved these changes
Looks good.

2023-07-12 19:59 UTC, merged