[CYB-175]  tableapi indexer throws ValidationException when writing to Hive
cloudera/cybersec pull request #52
Opened 2023-09-08 15:55 UTC by carolynduby

2023-09-11 13:07 UTC, stas-panasiuk requested changes

2023-09-11 13:07 UTC, stas-panasiuk commented on flink-cyber/flink-indexing/flink-indexing-hive/src/main/java/com/cloudera/cyber/indexing/hive/tableapi/TableApiAbstractJob.java
> +                .option("hive.storage.file-format", "orc");
this should be moved to the `TableApiHiveJob` class - you can override `fillTableOptions(...)` and append `super(...)` logic with this orc part.

2023-09-12 16:35 UTC, carolynduby commented on flink-cyber/flink-indexing/flink-indexing-hive/src/main/java/com/cloudera/cyber/indexing/hive/tableapi/TableApiAbstractJob.java
> +                .option("hive.storage.file-format", "orc");
Good point!  I made the change and checked it in.

2023-09-12 21:44 UTC, stas-panasiuk approved these changes

2023-09-14 13:18 UTC, merged