[CYB-201] [UI][COMPONENT] Multiple choice button.
cloudera/cybersec pull request #69
Opened 2024-02-28 13:59 UTC by vpavlenko-cv

2024-04-18 01:20 UTC, stas-panasiuk requested changes

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/flink-cyber-api/src/main/java/com/cloudera/cyber/indexing/MappingColumnDto.java
> +        return path;
If the main goal was to not use spring StringUtils, then you can just switch to  `org.apache.commons.lang3.StringUtils.isNotBlank` instead

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/src/main/java/com/cloudera/parserchains/queryservice/controller/ParserController.java
> +        Map<ParserID, ParserDescriptor> configs = parserDiscoveryService.describeAll();// TODO: check the feasibility of this check
It's better for readability to have comments on the new line instead

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/theme.scss
> +//);
Do we need this?

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/custom-palite.scss
I suppose you meant `custom-palette`

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-list-page/chain-list-page.component.ts
> +import {c} from "msw/lib/glossary-de6278a9";
is that an accidental import?

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/parser/parser.component.html
> -    <div class="parser-delete-btn-wrapper" nz-tooltip nzTitle="Remove Parser">
Why is the `nzTitle` removed? It might make sense to make it a tooltip text at least

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/chain-page/components/parser/parser.component.html
> -        nz-tooltip nzTitle="Click to edit name"
same as other comment

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/metron-parser-chain/parser-chains-config-service/frontend/parser-chains-client/src/app/cluster/cluster-page/cluster-page.component.ts
> +  // jobs$ = this.cluster$.pipe(map(cluster => cluster.jobs));
remove if not needed

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/flink-profiler/pom.xml
> +        </dependency>
Why do we need guava here?

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/flink-commands/json-commands/pom.xml
> +        </dependency>
do we need new dependencies here?

2024-04-18 01:20 UTC, stas-panasiuk commented on flink-cyber/flink-commands/scoring-commands/pom.xml
> +        </dependency>
do we need new dependencies here?

2024-04-19 11:03 UTC, vpavlenko-cv commented
Updating all pom files is required, because otherwise it uses transient dependencies from other mvn packages, which is not good, especially when they are marked as provided.

2024-04-19 15:48 UTC, stas-panasiuk approved these changes

2024-04-20 11:51 UTC, merged